// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissionStatistics.Data.DbContexts;

#nullable disable

namespace MissionStatistics.Data.Migrations
{
    [DbContext(typeof(MissionStatisticsDbContext))]
    partial class MissionStatisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("MissionStatistics.Domain.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Missions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Avenida Vieira Souto 168 Ipanema, Rio de Janeiro",
                            Agent = "007",
                            Country = "Brazil",
                            Date = new DateTime(1995, 12, 17, 21, 45, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rynek Glowny 12, Krakow",
                            Agent = "005",
                            Country = "Poland",
                            Date = new DateTime(2011, 4, 5, 17, 5, 12, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "27 Derb Lferrane, Marrakech",
                            Agent = "007",
                            Country = "Morocco",
                            Date = new DateTime(2001, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Rua Roberto Simonsen 122, Sao Paulo",
                            Agent = "005",
                            Country = "Brazil",
                            Date = new DateTime(1986, 5, 5, 8, 40, 23, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "swietego Tomasza 35, Krakow",
                            Agent = "011",
                            Country = "Poland",
                            Date = new DateTime(1997, 9, 7, 19, 12, 53, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Rue Al-Aidi Ali Al-Maaroufi, Casablanca",
                            Agent = "003",
                            Country = "Morocco",
                            Date = new DateTime(2012, 8, 29, 10, 17, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Rua tamoana 418, tefe",
                            Agent = "008",
                            Country = "Brazil",
                            Date = new DateTime(2005, 11, 10, 13, 25, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Zlota 9, Lublin",
                            Agent = "013",
                            Country = "Poland",
                            Date = new DateTime(2002, 10, 17, 10, 52, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Riad Sultan 19, Tangier",
                            Agent = "002",
                            Country = "Morocco",
                            Date = new DateTime(2017, 1, 1, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "atlas marina beach, agadir",
                            Agent = "009",
                            Country = "Morocco",
                            Date = new DateTime(2016, 12, 1, 21, 21, 21, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
